
version: '3.8'
services:
  app:
    build: .
    ports:
      - '4001:80'
    depends_on:
      - mongodb
      - broker
    environment:
      MONGO_URI: mongodb://mongodb:27017 
      MQTT_HOST: broker 
      MQTT_PORT: 1883 
      MQTT_CLIENT_ID: go-mqtt-client 
      MQTT_USERNAME: jinn 
      MQTT_PASSWORD: jinn 

  mongodb:
    image: mongo:7.0.5
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
  broker:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config:rw
      - ./docker/mosquitto/data:/mosquitto/data:rw
      - ./docker/mosquitto/log:/mosquitto/log:rw
    restart: unless-stopped
    

volumes:
  dbdata6:
  broker:
